[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A574FA60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4960fb7437a3229ca569d5d5b4a582a5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A574FF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4960fb7437a3229ca569d5d5b4a582a5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A574FCD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4960fb7437a3229ca569d5d5b4a582a5