[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A5796BB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ba7ad603bf5a2e14c9a9b1127ce3f337
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A5796850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ba7ad603bf5a2e14c9a9b1127ce3f337
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A575BD00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ba7ad603bf5a2e14c9a9b1127ce3f337