[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A58780D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/afbfc0e03d581f282645b668ca61d88b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A5878100>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/afbfc0e03d581f282645b668ca61d88b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A58781F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/afbfc0e03d581f282645b668ca61d88b