[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A5780CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dd9d0083d0d9e1e4f09f01830164e5a6
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A5780A30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dd9d0083d0d9e1e4f09f01830164e5a6
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A5748C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dd9d0083d0d9e1e4f09f01830164e5a6