[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A5780C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7cf19b42de7d87688d06d443ec03d201
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A5780040>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7cf19b42de7d87688d06d443ec03d201
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A574F730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7cf19b42de7d87688d06d443ec03d201