[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A5967A00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8b7999be5b79101407a537211277c8e8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A5967310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8b7999be5b79101407a537211277c8e8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A58178E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8b7999be5b79101407a537211277c8e8